// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerated from the docs/ folder structure.
  // Phase B fills in architecture / api / operations categories.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
