// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Two axes, each autogenerated from its own subfolder under docs/.
  docsSidebar: [{type: 'autogenerated', dirName: 'docs'}],
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
};

module.exports = sidebars;
